# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a5015ef0ac6fc9594151a6d20dd027ed4b6253d884936518346854a6cb563f5038d698238bd89e1bc4ee41b5354598721c10b3b0226df90b344f69364af11ae

test:
  secret_key_base: 44579726412ac24644bc6382a4d38641519bf2205969a24a12031d2e8353767ff09b15a4805e3289e850c7202544154689ae0027d910bc9e8c622da1ab18da92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
